name: Test Pull Request
on:
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.0.2

      - name: Test image
        uses: docker/build-push-action@v3.3.0
        with:
          target: test-base
          push: false
